In [39]:
import pandas as pd
import numpy as np
names = [x for x in range(0,17)]
df = pd.read_csv("bank.csv", sep = ';')
df.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [40]:
# no missing values.
df.isna().sum().sum()

0

In [42]:
#df_Y is the dataframe which includes the labels(classes) of the mushrooms.
df_Y = df['y']
df_Y

0       no
1       no
2       no
3       no
4       no
        ..
4516    no
4517    no
4518    no
4519    no
4520    no
Name: y, Length: 4521, dtype: object

In [44]:
# drop way for df_X.
df_X = df.drop('y',axis = 1)
df_X


age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome  
0     cellular   19   oct        79         1     -1         0  unknown  
1     cellular   11   may       220         1    339         4  failure  
2     cellular   16   apr       185         1    330         1  failure  
3      unknown    3   jun       199         4     -1         0  unknown  
4      unknown    5   may       226         1     -1         0  unknown  
...        ...  ...   ...       ...       ...    ...       ...      ...  
4516  cellular   30   jul       329         5     -1         0  unknown  
4517   unknown    9   may       153         1     -1         0  unknown  
4518  cellular   19   aug       151        11     -1         0  unknown  
4519  cellular    6   feb       129         4    211         3    other  
4520  cellular    3   apr       345         2    249         7    other  

[4521 rows x 16 columns]

In [45]:
df_X.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
dtype: object

In [49]:
# one hot encoding using one hot encoding from sklearn and give us numpy array instantly.
from sklearn.preprocessing import OneHotEncoder
X = OneHotEncoder().fit_transform(df_X).toarray()
print(X)
# one hot encoding only one column using LabelBinarizer.
from sklearn.preprocessing import LabelBinarizer
y = LabelBinarizer().fit_transform(df_Y)
# make the column  to array.
y = y.ravel()
y

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


array([0, 0, 0, ..., 0, 0, 0])

In [58]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [61]:
#x_train is the features matrix for training
#y_train is the labels for training
#x_test is test data
#y_test is test labels

#Support Vector Machine(SVM)
from sklearn import svm


# svm_clf = svm.LinearSVC()
# svm_clf.fit(x_train, y_train)

#K-NNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

# knn_clf = KNeighborsClassifier(n_neighbors=3)
# knn_clf.fit(x_train, y_train)

#Multilayer Perceptron(MLP)
from sklearn.neural_network import MLPClassifier

mlp_clf = MLPClassifier(random_state=1, max_iter=300)
mlp_clf.fit(x_train, y_train)




#Evaluation 
from sklearn.metrics import accuracy_score

y_pred = mlp_clf.predict(x_test)  #model ----> svm_clf, knn_clf, mlp_clf
print(accuracy_score(y_test, y_pred))


0.871039056742815
