In [97]:
import pandas as pd
import numpy as np
names = [x for x in range(0,7)]
df = pd.read_csv("car.data", names=names)
df.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [98]:
# no missing values.
df.isna().sum().sum()

0

In [99]:
#df_Y is the dataframe which includes the labels(classes) of the mushrooms.
df_Y = df[6]
df_Y

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...  
1723     good
1724    vgood
1725    unacc
1726     good
1727    vgood
Name: 6, Length: 1728, dtype: object

In [100]:
# drop way for df_X.
df_X = df.drop(6,axis = 1)
df_X


0      1      2     3      4     5
0     vhigh  vhigh      2     2  small   low
1     vhigh  vhigh      2     2  small   med
2     vhigh  vhigh      2     2  small  high
3     vhigh  vhigh      2     2    med   low
4     vhigh  vhigh      2     2    med   med
...     ...    ...    ...   ...    ...   ...
1723    low    low  5more  more    med   med
1724    low    low  5more  more    med  high
1725    low    low  5more  more    big   low
1726    low    low  5more  more    big   med
1727    low    low  5more  more    big  high

[1728 rows x 6 columns]

In [101]:
df_X.dtypes

0    object
1    object
2    object
3    object
4    object
5    object
dtype: object

In [102]:
# one hot encoding using one hot encoding from sklearn and give us numpy array instantly.
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
X = OneHotEncoder().fit_transform(df_X).toarray()
print(X)
# one hot encoding only one column using LabelBinarizer.
from sklearn.preprocessing import LabelEncoder
print(type(df_Y))
y = LabelEncoder().fit_transform(df_Y)

# make the column  to array.
y = y.ravel()
y


[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 1. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 1. 0. 0.]]
<class 'pandas.core.series.Series'>


array([2, 2, 2, ..., 2, 1, 3])

In [103]:
print(X.shape)
y.shape


(1728, 21)


(1728,)

In [104]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [105]:
#x_train is the features matrix for training
#y_train is the labels for training
#x_test is test data
#y_test is test labels

#Support Vector Machine(SVM)
from sklearn import svm


svm_clf = svm.LinearSVC()
svm_clf.fit(x_train, y_train)

#K-NNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(x_train, y_train)

#Multilayer Perceptron(MLP)
from sklearn.neural_network import MLPClassifier

mlp_clf = MLPClassifier(random_state=1, max_iter=300)
mlp_clf.fit(x_train, y_train)




#Evaluation 
from sklearn.metrics import accuracy_score

y_pred = knn_clf.predict(x_test)  #model ----> svm_clf, knn_clf, mlp_clf
print("knn {}".format(accuracy_score(y_test, y_pred)))
y_pred = mlp_clf.predict(x_test)  #model ----> svm_clf, knn_clf, mlp_clf
print("mlp {}".format(accuracy_score(y_test, y_pred)))
y_pred = svm_clf.predict(x_test)  #model ----> svm_clf, knn_clf, mlp_clf
print("svm {}".format(accuracy_score(y_test, y_pred)))


knn 0.8497109826589595
mlp 0.9749518304431599
svm 0.8901734104046243


c:\users\marios\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
